const defaults=[
 {title:'Pass Rush',stat:'20',label:'Sacks',rank:'32nd NFL',severity:'Pass rush collapse',status:'pending',evidence:['Osa Odighizuwa added','Romelo Height drafted','Grayson Halton drafted']},
 {title:'Interceptions',stat:'6',label:'INTs Forced',rank:'32nd NFL',severity:'No takeaway threat',status:'notfixed',evidence:['Still needs proven ball production','Secondary must create more plays']},
 {title:'Red Zone D',stat:'29',label:'TDs Allowed',rank:'Worst NFL',severity:'Could not finish drives defensively',status:'pending',evidence:['Front seven rebuilt','Must prove it inside the 20']},
 {title:'Run Game',stat:'3.78',label:'Yards/Carry',rank:'30th NFL',severity:'Inefficient rushing attack',status:'pending',evidence:['Kaelon Black added','More OL competition','Needs explosive-run rebound']},
 {title:'Turnovers',stat:'23',label:'Giveaways',rank:'27th NFL',severity:'Too many empty possessions',status:'notfixed',evidence:['Decision-making must improve','Ball security is not solved on paper']},
 {title:'Penalties',stat:'106',label:'Penalties',rank:'3rd Most',severity:'Self-inflicted damage',status:'notfixed',evidence:['Discipline must improve','Cannot be fully fixed by roster moves']}
];
let problems=JSON.parse(localStorage.getItem('fixTrackerProblems')||'null')||defaults;
let mode='setup',current=0,editing=0,drawer=false,studio=false,revealStep=0,flash='';
const app=document.getElementById('app');
const save=()=>localStorage.setItem('fixTrackerProblems',JSON.stringify(problems));
const cls=s=>s==='fixed'?'fixed':s==='pending'?'pending':'notfixed';
const sym=s=>s==='fixed'?'👍':s==='pending'?'🟡':'👎';
const label=s=>s==='fixed'?'Fixed':s==='pending'?'Pending':'Not Fixed';
function render(){ document.body.className=`${studio?'studio-on':''} ${flash}`; if(mode==='setup') renderSetup(); if(mode==='board') renderBoard(); if(mode==='problem') renderProblem(); }
function renderSetup(){const p=problems[editing]||problems[0]; document.body.className=''; app.innerHTML=`
  <div class="topbar"><div class="brand"><div class="mark">SF</div>49ers Fix Tracker</div><button class="primary-btn" onclick="launch()">Launch Presentation</button></div>
  <section class="setup"><div class="setup-hero"><div><h1>Control Room</h1><p>Build the episode here. The audience only sees the fullscreen broadcast graphics.</p></div><button class="ghost-btn" onclick="resetData()">Reset Defaults</button></div>
  <div class="setup-grid"><div class="panel">
    <div class="issue-editor">
      ${field('Problem Title','title',p.title)}${field('Main Stat','stat',p.stat)}${field('Stat Label','label',p.label)}${field('NFL Rank','rank',p.rank)}
      <div class="stack"><div class="label">Status</div><select onchange="updateField('status',this.value)"><option value="fixed" ${p.status==='fixed'?'selected':''}>Fixed</option><option value="pending" ${p.status==='pending'?'selected':''}>Pending</option><option value="notfixed" ${p.status==='notfixed'?'selected':''}>Not Fixed</option></select></div>
      ${field('Severity Line','severity',p.severity)}
      <div class="stack" style="grid-column:1/-1"><div class="label">Evidence Bullets — one per line</div><textarea onchange="updateEvidence(this.value)">${p.evidence.join('\n')}</textarea></div>
      <div class="editor-actions"><button class="ghost-btn" onclick="addProblem()">Add Problem</button><button class="danger-btn" onclick="deleteProblem()">Delete</button><button class="ghost-btn" onclick="move(-1)">Move Up</button><button class="ghost-btn" onclick="move(1)">Move Down</button></div>
    </div>
    <div class="issue-list">${problems.map((x,i)=>`<div class="mini-card ${i===editing?'active':''}" onclick="editing=${i};render()"><div class="handle">${i+1}</div><div><div class="mini-title">${x.title}</div><div class="mini-sub">${x.stat} ${x.label} · ${x.rank}</div></div><span class="badge ${cls(x.status)}">${label(x.status)}</span></div>`).join('')}</div>
  </div><div class="panel production-note"><b>Studio hotkeys</b><br><br><span class="kbd">S</span> studio mode &nbsp; <span class="kbd">Space</span> reveal/next<br><span class="kbd">←</span>/<span class="kbd">→</span> move &nbsp; <span class="kbd">1-9</span> jump<br><span class="kbd">B</span> board &nbsp; <span class="kbd">M</span> controls<br><br>Studio Mode hides website chrome for recording.</div></div></section>`;}
function field(l,k,v){return `<div class="stack"><div class="label">${l}</div><input value="${String(v).replaceAll('"','&quot;')}" onchange="updateField('${k}',this.value)"></div>`}
function updateField(k,v){problems[editing][k]=v;save();render()}function updateEvidence(v){problems[editing].evidence=v.split('\n').filter(Boolean);save();render()}
function addProblem(){problems.push({title:'New Problem',stat:'0',label:'Stat',rank:'Rank',severity:'Why it mattered',status:'pending',evidence:['Evidence item']});editing=problems.length-1;save();render()}
function deleteProblem(){if(problems.length<2)return;problems.splice(editing,1);editing=Math.max(0,editing-1);save();render()}function move(d){let ni=editing+d;if(ni<0||ni>=problems.length)return;[problems[editing],problems[ni]]=[problems[ni],problems[editing]];editing=ni;save();render()}function resetData(){problems=structuredClone(defaults);editing=0;save();render()}function launch(){mode='board';current=0;revealStep=0;render()}function fixedCount(){return problems.filter(p=>p.status==='fixed').length}
function controls(){return `<div class="hidden-controls" onmouseenter="showDrawer()"></div><div class="drawer ${drawer&&!studio?'show':''}" onmouseleave="hideDrawer()"><button class="ghost-btn" onclick="mode='setup';render()">Setup</button><button class="ghost-btn" onclick="mode='board';render()">Board</button><button class="ghost-btn" onclick="prev()">Prev</button><button class="primary-btn" onclick="next()">Next</button><button class="ghost-btn" onclick="studio=!studio;render()">Studio</button></div>`}
function renderBoard(){revealStep=0;app.innerHTML=`${controls()}<section class="stage"><div class="board"><div class="board-head"><div class="big-score count-score">${fixedCount()} / ${problems.length}</div><h1>Problems Fixed</h1></div><div class="tile-grid">${problems.map((p,i)=>`<div class="tile ${cls(p.status)}" onclick="current=${i};mode='problem';revealStep=0;render()"><div><h2>${p.title}</h2><div class="tile-stat">${p.stat} ${p.label} · ${p.rank}</div></div><div class="status-symbol ${cls(p.status)}">${sym(p.status)}</div></div>`).join('')}</div><div class="final-line">Roster moves were made. Production will tell the story.</div></div></section>`}
function renderProblem(){const p=problems[current];const visible=p.evidence.slice(0,revealStep);const locked=revealStep>0;app.innerHTML=`${controls()}<section class="stage ${flash}"><div class="score"><div class="score-num">${current+1}/${problems.length}</div><div class="score-label">Critical Issue</div></div><div class="problem-card ${cls(p.status)} ${locked?'locked':''}"><div class="studio-label">2025 Critical Issue</div><div class="stat-side"><h1 class="problem-title">${p.title}</h1><div class="stat-number" data-value="${p.stat}">${p.stat}</div><div class="stat-label">${p.label}</div><div class="rank">${p.rank}</div></div><div class="story-side"><div class="ask">Was it fixed?</div><div class="status-lock ${cls(p.status)}">${sym(p.status)} ${label(p.status)}</div><div class="verdict-buttons ${studio?'hide-in-studio':''}"><button class="verdict-btn" onclick="setStatus('fixed')">👍 Yes / Fixed</button><button class="verdict-btn" onclick="setStatus('pending')">🟡 Pending</button><button class="verdict-btn" onclick="setStatus('notfixed')">👎 No / Not Fixed</button></div><div class="evidence ${visible.length?'show':''}"><h3>Why</h3><ul>${visible.map((e,i)=>`<li style="animation-delay:${i*90}ms">✓ ${e}</li>`).join('')}</ul></div><div class="studio-hint">Space reveals evidence · Arrow moves next</div></div></div></section>`; animateStat();}
function animateStat(){const el=document.querySelector('.stat-number'); if(!el)return; const raw=el.dataset.value; const target=parseFloat(raw); if(Number.isNaN(target))return; let start=performance.now(); const dur=520; const decimals=(raw.split('.')[1]||'').length; function tick(t){const p=Math.min(1,(t-start)/dur); const ease=1-Math.pow(1-p,3); el.textContent=(target*ease).toFixed(decimals); if(p<1)requestAnimationFrame(tick); else el.textContent=raw;} requestAnimationFrame(tick);}
function triggerFlash(s){flash=s==='fixed'?'flash-fixed':s==='notfixed'?'flash-bad':'flash-pending'; render(); setTimeout(()=>{flash='';render()},650)}
function setStatus(s){problems[current].status=s;save();revealStep=Math.max(1,revealStep);triggerFlash(s)}
function next(){ if(mode==='setup'){launch();return} if(mode==='problem'&&revealStep<problems[current].evidence.length){revealStep++;render();return} if(mode==='board'){mode='problem';current=0;revealStep=0}else if(current<problems.length-1){current++;mode='problem';revealStep=0}else{mode='board';revealStep=0} render()}
function prev(){ if(mode==='problem'&&revealStep>0){revealStep--;render();return} if(mode==='problem'&&current>0){current--;revealStep=0;render()}else{mode='board';render()}}
function showDrawer(){drawer=true;render()}function hideDrawer(){drawer=false;render()}
document.addEventListener('keydown',e=>{if(e.key===' '||e.key==='ArrowRight'){e.preventDefault();next()} if(e.key==='ArrowLeft'){prev()} if(e.key.toLowerCase()==='b'){mode='board';render()} if(e.key.toLowerCase()==='v'){mode='board';render()} if(e.key.toLowerCase()==='m'){drawer=!drawer;render()} if(e.key.toLowerCase()==='h'){drawer=false;render()} if(e.key.toLowerCase()==='s'){studio=!studio;drawer=false;render()} if(/[1-9]/.test(e.key)){let n=Number(e.key)-1;if(n<problems.length){current=n;mode='problem';revealStep=0;render()}}});render();
