const DEFAULTS = [
  { title:'Pass Rush', stat:'20', label:'Sacks', rank:'32nd NFL', severity:'Pass rush collapse', status:'pending', included:true, evidence:['Osa Odighizuwa added','Romelo Height drafted','Grayson Halton drafted'] },
  { title:'Interceptions', stat:'6', label:'INTs Forced', rank:'32nd NFL', severity:'Could not create takeaways', status:'pending', included:true, evidence:['Added ball-hawk secondary competition','Coverage communication must improve','Still needs 2026 proof'] },
  { title:'Red Zone D', stat:'29', label:'TDs Allowed', rank:'Worst NFL', severity:'Worst red zone defense', status:'pending', included:true, evidence:['Added size to defensive front','New personnel packages','Needs real-game stops'] },
  { title:'Run Game', stat:'3.78', label:'Yards/Carry', rank:'30th NFL', severity:'Rushing efficiency problem', status:'pending', included:true, evidence:['Kaelon Black drafted','OL depth and competition added','Run game still unproven'] },
  { title:'Turnovers', stat:'23', label:'Giveaways', rank:'27th NFL', severity:'Turnover problem', status:'notfixed', included:true, evidence:['Decision-making must improve','Ball security is not solved on paper'] },
  { title:'Penalties', stat:'106', label:'Penalties', rank:'3rd Most', severity:'Discipline problem', status:'notfixed', included:true, evidence:['Coaching emphasis only','Cannot be fixed until games are played'] }
];
let state = JSON.parse(localStorage.getItem('fixTrackerStudio') || 'null') || { problems: DEFAULTS, selected:0, mode:'setup', reveal:false, clean:false };
const app = document.getElementById('app');
const flash = document.getElementById('flash');
const save = () => localStorage.setItem('fixTrackerStudio', JSON.stringify(state));
const episode = () => state.problems.filter(p=>p.included);
const activeProblem = () => episode()[state.selected] || episode()[0] || state.problems[0];
function fixedCount(){ return episode().filter(p=>p.status === 'fixed').length; }
function statusText(s){ return s==='fixed'?'YES / FIXED':s==='notfixed'?'NO / NOT FIXED':'PENDING'; }
function statusIcon(s){ return s==='fixed'?'👍':s==='notfixed'?'👎':'●'; }
function clsStatus(s){ return s==='notfixed'?'notfixed':s; }
function triggerFlash(type){ flash.className = 'flash ' + (type || 'gold'); setTimeout(()=>flash.className='flash',700); }
function updateProblem(i, key, val){ state.problems[i][key]=val; save(); render(); }
function selectProblem(i){ state.selected = Math.max(0, episode().findIndex(p=>p===state.problems[i])); if(state.selected<0) state.selected=0; state.reveal=false; save(); render(); }
function setMode(mode){ state.mode=mode; state.reveal=false; save(); render(); }
function setStatus(s){ const p=activeProblem(); const idx=state.problems.indexOf(p); state.problems[idx].status=s; state.reveal=true; save(); triggerFlash(s==='fixed'?'green':s==='notfixed'?'red':'gold'); render(); }
function moveProblem(dir){ const p = activeProblem(); const i = state.problems.indexOf(p); const j = i + dir; if(j<0||j>=state.problems.length) return; [state.problems[i],state.problems[j]]=[state.problems[j],state.problems[i]]; save(); render(); }
function next(){ const ep=episode(); state.selected = Math.min(ep.length-1, state.selected+1); state.reveal=false; save(); triggerFlash('gold'); render(); }
function prev(){ state.selected = Math.max(0, state.selected-1); state.reveal=false; save(); triggerFlash('gold'); render(); }
function addProblem(){ state.problems.push({title:'New Problem',stat:'0',label:'Stat',rank:'NFL Rank',severity:'Critical issue',status:'pending',included:true,evidence:['Evidence item']}); state.selected=episode().length-1; save(); render(); }
function delProblem(){ if(state.problems.length<=1) return; const p=activeProblem(); const i=state.problems.indexOf(p); state.problems.splice(i,1); state.selected=0; save(); render(); }
function reset(){ if(confirm('Reset to default problems?')){ state={ problems: DEFAULTS, selected:0, mode:'setup', reveal:false, clean:false }; save(); render(); } }
function renderSetup(){ const p = activeProblem(); const idx = state.problems.indexOf(p); app.innerHTML = `<div class="app">
  <div class="topbar"><div class="brand"><div class="logo">SF</div><div>49ERS FIX TRACKER<small>BROADCAST PRODUCTION TOOL</small></div></div><div><button class="btn ghost" onclick="reset()">RESET DEFAULTS</button> <button class="btn primary" onclick="setMode('stage')">LAUNCH PRESENTATION</button></div></div>
  <section class="hero-row"><div><div class="eyebrow">PRODUCER SETUP</div><h1 class="page-title">CONTROL ROOM</h1><div class="subtitle">Build the episode. The audience only sees the clean fullscreen graphics.</div></div><div class="score-mini"><b>${fixedCount()} / ${episode().length}</b><span>PROBLEMS FIXED</span></div></section>
  <section class="setup-grid"><div class="panel">
    <div class="include">INCLUDE IN THIS EPISODE <input type="checkbox" ${p.included?'checked':''} onchange="updateProblem(${idx},'included',this.checked)"></div>
    <div class="form-grid">
      <div><label>Problem Title</label><input value="${p.title}" oninput="updateProblem(${idx},'title',this.value)"></div>
      <div><label>Main Stat</label><input value="${p.stat}" oninput="updateProblem(${idx},'stat',this.value)"></div>
      <div><label>Stat Label</label><input value="${p.label}" oninput="updateProblem(${idx},'label',this.value)"></div>
      <div><label>NFL Rank</label><input value="${p.rank}" oninput="updateProblem(${idx},'rank',this.value)"></div>
      <div><label>Status</label><select onchange="updateProblem(${idx},'status',this.value)"><option value="fixed" ${p.status==='fixed'?'selected':''}>Fixed</option><option value="pending" ${p.status==='pending'?'selected':''}>Pending</option><option value="notfixed" ${p.status==='notfixed'?'selected':''}>Not Fixed</option></select></div>
      <div><label>Severity Line</label><input value="${p.severity}" oninput="updateProblem(${idx},'severity',this.value)"></div>
      <div class="span2"><label>Evidence Bullets — one per line</label><textarea oninput="updateProblem(${idx},'evidence',this.value.split('\n').filter(Boolean))">${p.evidence.join('\n')}</textarea></div>
    </div>
    <div class="row-actions"><button class="btn" onclick="addProblem()">ADD PROBLEM</button><button class="btn" onclick="delProblem()">DELETE</button><button class="btn" onclick="moveProblem(-1)">MOVE UP</button><button class="btn" onclick="moveProblem(1)">MOVE DOWN</button></div>
    <div class="problem-list">${state.problems.map((x,i)=>`<button class="mini-card ${x===p?'active':''}" onclick="selectProblem(${i})"><span class="num">${i+1}</span><span><span class="mini-title">${x.title}</span><span class="mini-meta">${x.stat} ${x.label} · ${x.rank}</span></span><span class="badge ${clsStatus(x.status)}">${statusText(x.status)}</span></button>`).join('')}</div>
  </div><div class="panel help-panel"><div class="eyebrow">RECORDING SHORTCUTS</div><div class="help-title">PRESENTATION<br>CONTROLS</div><p><span class="key">Space</span> next &nbsp; <span class="key">←</span>/<span class="key">→</span> move</p><p><span class="key">B</span> board &nbsp; <span class="key">V</span> verdict &nbsp; <span class="key">M</span> controls</p><p><span class="key">C</span> clean mode &nbsp; <span class="key">H</span> hide controls</p><div class="note">Use Chrome fullscreen before recording. Hover the far-left edge to bring back hidden controls.</div></div></section></div>`;
}
function renderStage(){ const ep=episode(); const p=activeProblem(); const cardCls = state.reveal ? clsStatus(p.status) : ''; app.innerHTML = `<div class="stage ${state.clean?'clean':''}"><div class="progress"><b>${state.selected+1}/${ep.length}</b><span>PROBLEM</span></div><div class="broadcast-card ${cardCls}"><section class="left"><span class="issue-label">2025 CRITICAL ISSUE</span><h1 class="issue-title">${p.title.toUpperCase()}</h1><div class="statline"><div class="stat-number" data-target="${p.stat}">${p.stat}</div><div class="stat-side"><div class="label">${p.label.toUpperCase()}</div><div class="rank">${p.rank.toUpperCase()}</div></div></div><div class="severity">${p.severity.toUpperCase()}</div></section><section class="right"><div class="question">WAS IT FIXED?</div>${state.reveal?`<div class="status-lock ${clsStatus(p.status)}">${statusIcon(p.status)} ${statusText(p.status)}</div>`:''}<div class="verdict-buttons"><button class="choice" onclick="setStatus('fixed')">👍 YES / FIXED</button><button class="choice" onclick="setStatus('pending')">● PENDING</button><button class="choice" onclick="setStatus('notfixed')">👎 NO / NOT FIXED</button></div><button class="reveal-btn" onclick="state.reveal=true;save();render();">REVEAL EVIDENCE</button>${state.reveal?`<div class="evidence">${p.evidence.map(e=>`<div class="evidence-item">✓ ${e}</div>`).join('')}</div>`:''}</section></div>${controls()}</div>`; animateNumber(); }
function controls(){ return `<div class="hidden-controls"><div class="drawer"><button onclick="setMode('setup')">Setup</button><button onclick="setMode('board')">Board</button><button onclick="prev()">Prev</button><button onclick="next()">Next</button><button onclick="state.clean=!state.clean;save();render();">Clean</button></div></div>`; }
function renderBoard(){ const ep=episode(); app.innerHTML = `<div class="board"><div class="board-head"><div class="board-kicker">2025 PROBLEM FIX TRACKER</div><div class="board-score"><span class="red" id="scoreCount">${fixedCount()}</span> / ${ep.length}</div><div class="board-title">PROBLEMS FIXED</div><div class="board-sub">ROSTER MOVES WERE MADE. PRODUCTION WILL TELL THE STORY.</div></div><div class="tile-grid">${ep.map((p,i)=>`<button class="tile ${clsStatus(p.status)}" onclick="state.selected=${i};setMode('stage')"><span class="big-num">${String(i+1).padStart(2,'0')}</span><h3>${p.title.toUpperCase()}</h3><p>${p.stat} ${p.label} · ${p.rank}</p><span class="badge tile-badge ${clsStatus(p.status)}">${statusIcon(p.status)} ${statusText(p.status)}</span></button>`).join('')}</div><div class="footer-line">CLICK ANY PROBLEM TO OPEN THE FULL-SCREEN BROADCAST CARD</div>${controls()}</div>`; animateScore(); }
function animateNumber(){ const el=document.querySelector('.stat-number'); if(!el) return; const target=parseFloat(el.dataset.target); if(isNaN(target)) return; const decimals = String(el.dataset.target).includes('.') ? 2 : 0; let start=null; const dur=520; function step(ts){ if(!start) start=ts; const p=Math.min(1,(ts-start)/dur); const eased=1-Math.pow(1-p,3); el.textContent=(target*eased).toFixed(decimals).replace(/\.00$/,''); if(p<1) requestAnimationFrame(step); } requestAnimationFrame(step); }
function animateScore(){ const el=document.getElementById('scoreCount'); if(!el) return; const target=fixedCount(); let start=null; function step(ts){ if(!start) start=ts; const p=Math.min(1,(ts-start)/700); el.textContent=Math.round(target*(1-Math.pow(1-p,3))); if(p<1) requestAnimationFrame(step); } requestAnimationFrame(step); }
function render(){ if(state.mode==='stage') renderStage(); else if(state.mode==='board') renderBoard(); else renderSetup(); }
document.addEventListener('keydown', e=>{ if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)) return; if(e.code==='Space'){ e.preventDefault(); if(state.mode==='stage' && !state.reveal){ state.reveal=true; save(); render(); } else next(); } if(e.key==='ArrowRight') next(); if(e.key==='ArrowLeft') prev(); if(e.key.toLowerCase()==='b') setMode('board'); if(e.key.toLowerCase()==='v') setMode('board'); if(e.key.toLowerCase()==='m') setMode('setup'); if(e.key.toLowerCase()==='c'){ state.clean=!state.clean; save(); render(); } if(e.key.toLowerCase()==='h'){ state.clean=true; save(); render(); } });
render();
